accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.register_view, name='signup-view'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('profile/', views.current_user_profile, name="current_user_profile"),
    path('update_profile/', views.update_user_profile, name='update_user_profile'),
    #  URL's referentes ao reset de senha
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html",
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"
    ), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name = "accounts/password_reset_confirm.html"
    ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html"
    ), name='password_reset_complete'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
]

posts/urls.py
from . import views
from django.urls import path


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:id>/', views.post_detail, name='post-detail'),
    path('create_post/', views.create_post, name='create_post'),
]

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


"""
    class profile:
        bio = 
        profile_imagem = 
        address = 
        user = 
"""
class Profile(models.Model):
    bio = models.TextField()
    profile_image = models.URLField(max_length=500)
    address = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def __str__(self) -> str:
        return f'<Profile> for {self.user.username}'

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


"""
    class Post
        -id: int
        -title: varchar
        -body: text
        -created_at: datetime
        -updated_at: datetime
"""
User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=225)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self) -> str:
        return self.title
    
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Profile


User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'address']

        labels = {
            'address': 'Endereço'
        }

        widgets = {
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control mb-3 mt-2'
                }
            ),
            'bio': forms.Textarea(
                attrs={
                    'class': 'form-control mt-2'
                }
            )
        }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username']

        labels = {
            'first_name': 'Primeiro nome',
            'last_name': 'Sobrenome',
            'username': 'Usuário'
        }

        widgets = {
            'first_name': forms.TextInput(
                attrs= {
                    'class': 'form-control mb-2'
                }
            ),
            'last_name': forms.TextInput(
                attrs= {
                    'class': 'form-control mb-2'
                }
            ),
            'username': forms.TextInput(
                attrs= {
                    'class': 'form-control mb-2'
                }
            )
        }

posts/forms.py
from django import forms
from .models import Post


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
        labels = {
            'title': 'Título',
            'body': 'Mensagem'
        }

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control mb-3'
                }
            ),

            'body': forms.Textarea(
                attrs={
                    'class': 'form-control',
                }
            ),
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from posts.models import Post
from django.contrib.auth.decorators import login_required


def register_view(request):
    form = UserRegistrationForm()

    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('accounts:login_page')

    context = {
        'form': form,
    }

    return render(request, 'accounts/register.html', context) 

def login_page(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user_authenticated = authenticate(username=username, password=password)

            if user_authenticated is not None:
                login(request, user_authenticated)

                return redirect('posts:index')

    context = {
        'form': form
    }

    return render(request, 'accounts/login.html', context)

def logout_page(request):
    logout(request)

    return redirect('posts:index')

@login_required
def current_user_profile(request):
    user = request.user
    posts = Post.objects.filter(author=user).all().order_by('-created_at')

    context = {
        'user': user,
        'posts': posts
    }

    return render(request, 'accounts/profile.html', context)

@login_required
def update_user_profile(request):
    user_form = UserUpdateForm(instance=request.user)
    profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    if request.method == "POST":
        profile_form = ProfileUpdateForm(instance=request.user.profile, data={
            'bio': request.POST.get('bio', None),
            'address': request.POST.get('address', None)
        })
        user_form = UserUpdateForm(instance=request.user, data={
            'first_name': request.POST.get('first_name', None),
            'username': request.POST.get('username', None),
            'last_name': request.POST.get('last_name', None)
        })

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()

            return redirect('accounts:current_user_profile')

    context = {
        'profile_form': profile_form,
        'user_form': user_form,
    }

    return render(request, 'accounts/updateprofile.html', context)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostCreationForm
from django.contrib.auth.decorators import login_required


def index(request):
    posts = Post.objects.all().order_by('-created_at')

    return render(request, 'posts/index.html', {'posts': posts})

def post_detail(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post': post
    }

    return render(request, 'posts/detail.html', context)

@login_required
def create_post(request):
    form = PostCreationForm()

    if request.method == "POST":
        form = PostCreationForm(request.POST)
        if form.is_valid():
            form_obj = form.save(commit=False)
            form_obj.author = request.user
            form_obj.save()

            return redirect('posts:index')

    context = {
        'form': form
    }

    return render(request, 'posts/create_post.html', context)

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Entrar</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Entrar" class="mt-2 btn btn-primary"><br><br>
        <a href="{% url 'accounts:password_reset' %}">Esqueci minha senha</a>
    </form>
    <br><br><br>

{% endblock content %}

templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Redefina sua senha</h1>
    <p>Informe o endereço de email associado à sua conta</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Redefinir a Senha" class="btn btn-primary mt-2">
        <small><p><a href="{% url 'accounts:login_page' %}">Entrar</a></p></small>
    </form>
{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}
    <p>Você redefiniu sua senha com sucesso.</p>
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Troque sua senha</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Trocar senha">
    </form>
{% endblock content %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

    <p>Um email foi enviado com instruções para Redefinir sua senha.</p>

{% endblock content %}

templates/accounts/password_reset_email.html
<p>Clique no link para redefinir sua senha</p>
<a href="{{ protocol }}:{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">Redefina sua senha</a>


{{ protocol }}:{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<section style="background-color: #fff">
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
                <!-- src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"-->
              <img
                src="{{ user.profile.profile_image }}"
                alt="avatar"
                class="rounded-circle img-fluid"
                style="width: 150px"
              />
              <h5 class="my-3">{{ user.username }}</h5>
              <p class="text-muted mb-1">{{ user.profile.bio }}</p>
              <p class="text-muted mb-4">{{ user.profile.address }}</p>
              <div class="d-flex justify-content-center mb-2">
                <a href="{% url 'accounts:update_user_profile' %}" class="btn btn-primary">Editar Perfil</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Nome completo</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                </div>
              </div>
              <hr />
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.email }}</p>
                </div>
              </div>
              <hr />
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Address</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ user.profile.address }}</p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            {% if posts %}
                {% for post in posts %}
                    <article class="blog-post">
                    <h2 class="blog-post-title mb-1">{{ post.title }}</h2>
                    <p class="blog-post-meta">{{ post.created_at }}</p>

                    <p>
                        {{ post.body|truncatewords:30 }}
                    </p>
                    <hr />
                    </article>
                {% endfor %}
            {% else %}
                <h3>Você não tem nenhuma postagem. <br></h3>
                <a href="{% url 'posts:create_post' %}"> Crie usua Primeira</a>
            {% endif %}
            
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <h1>Crie sua conta</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" value="Enviar" class="btn btn-primary">Enviar</button>
    </form>

{% endblock content %}

templates/accounts/updateprofile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section style="background-color: #fff">
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
                <!-- src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"-->
              <img
                src="{{ user.profile.profile_image }}"
                alt="avatar"
                class="rounded-circle img-fluid"
                style="width: 150px"
              />
              <h5 class="my-3">{{ user.username }}</h5>
              <p class="text-muted mb-1">{{ user.profile.bio }}</p>
              <p class="text-muted mb-4">{{ user.profile.address }}</p>

            </div>
          </div>
        </div>
        <div class="col-lg-8">
            <h1>Atualizar Informações do Usuário</h1>
            <form action="" method="post">
                {% csrf_token %}
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                <input type="submit" value="Salvar" class="btn btn-success">
            </form>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TDD- Django Blog </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'posts:index' %}">TDD - Blog</a>
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'posts:index' %}">Página Inicial</a>
                  </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:create_post' %}">Criar Post</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:current_user_profile' %}">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout_page' %}">Sair</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup-view' %}">Registrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login_page' %}">Entrar</a>
                    </li>
                  {% endif %}
                  
                </ul>
                <form class="d-flex" role="search">
                  <input
                    class="form-control me-2"
                    type="search"
                    placeholder="Search"
                    aria-label="Search"
                  />
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </header>

    <main class="container">
      {% block content %}

      {% endblock content %}
      <footer class="blog-footer">
        <p class="text text-center">&copy; <a href="">TDD Blog 2023</a>
        <p class="text text-end">
          <a href="#">Voltar ao Topo</a>
        </p>
    </footer>
    </main>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/posts/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Publicar" class="btn btn-primary mt-2">
    </form>
    <br><br><br>
{% endblock content %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p>{{ post.body }}</p>
    <small>Publicado em: {{ post.created_at }}</small> 

{% endblock content %}

templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="text text-center p-4 p-md-5 mb-4 rounded text-bg-dark">
        <div class="text text-center col-md-6 px-0">
          <h1 class="display-4 fst-italic">Bem vindo ao Blog TDD-Django</h1>
          <p class="lead my-3">
            Essa é uma aplicação simples criada enquanto estou aprendendo TDD com Django 
          </p>
        </div>
      </div>
    
    {% for post in posts %}
        <article class="blog-post">
            <h2 class="blog-post-title mb-1"><a href="{% url 'posts:post-detail' post.id %}"> {{ post.title }}</a></h2>
            <p class="blog-post-meta">{{ post.created_at }} por <a href="#">{{ post.author }}</a></p>
            <p>
              {{ post.body|truncatewords:30 }}
            </p>
            <hr />
          </article>
    {% endfor %}

{% endblock content %}